### ISSUE TITLE
Update status regarding Master Thesis

### ISSUE THREAD

**Issue by AntonFriberg** [adamhagglund/adamhagglund.github.io#2]
Hi! Hope all is well with you!

Happened to have a look at this site today while slow-browsing github. Just a friendly reminder that this information is no longer correct. Congratulations to the Master's Degree btw.

https://github.com/adamhagglund/adamhagglund.github.io/blob/64f5fd832e78dc65f23a0dc4e590b8039a84ba8e/index.html#L126

**Comment by adamhagglund** [comment]
Finally done! 😆 Hope all is well with you Anton!
